swagger: "2.0"
info:
  title: "Meme Platform"
  description: "Platform for memes."
  version: "1.0.0"
host: "TBA"

tags:
- name: "users"
  description: "Registered users"
- name: "memes"
  description: "Created meme posts"
- name: "templates"
  description: "Template images"
- name: "comments"
  description: "Comments on meme posts"
- name: "categories"
  description: "Categories of memes"
  
paths:
  # ============== USERS ==============
  /users:
    post:
      tags:
      - "users"
      summary: "Register a new user"
      consumes:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
    get:
      tags:
      - "users"
      summary: "Get a list of users"
      produces:
      - "application/json"
      parameters:
      - name: "namequery"
        in: "query"
        description: "search query for usernames"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        400:
          description: "Invalid parameters or values"
        500:
          description: "Internal server error"
  /users/{username}:
    get:
      tags:
      - "users"
      summary: "Get a user"
      parameters:
      - name: "username"
        in: "path"
        description: "username of the user to get"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
    put:
      tags:
      - "users"
      summary: "Edits a user"
      parameters:
      - name: "username"
        in: "path"
        description: "username of the user to edit"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
    delete:
      tags:
      - "users"
      summary: "Removes a user"
      parameters:
      - name: "username"
        in: "path"
        description: "username of the user to delete"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
  
  # ============== MEMES ==============
  /memes:
    post:
      tags:
      - "memes"
      summary: "Post a new meme"
      responses:
        200:
          description: "successful operation"
    get:
      tags:
      - "memes"
      summary: "Get a list of memes"
      responses:
        200:
          description: "successful operation"
  /memes/{memeId}:
    get:
      tags:
      - "memes"
      summary: "Get a meme"
      parameters:
      - name: "memeId"
        in: "path"
        description: "id of the meme to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
    delete:
      tags:
      - "memes"
      summary: "Delete a meme"
      parameters:
      - name: "memeId"
        in: "path"
        description: "id of the meme to delete"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
      
  # ============== TEMPLATES ==============
  /templates:
    post:
      tags:
      - "templates"
      summary: "Create a new meme template"
      responses:
        200:
          description: "successful operation"
    get:
      tags:
      - "templates"
      summary: "Get a list of memes"
      responses:
        200:
          description: "successful operation"
  /templates/{templateId}:
    get:
      tags:
      - "templates"
      summary: "Get a template"
      parameters:
      - name: "templateId"
        in: "path"
        description: "id of the template to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
    delete:
      tags:
      - "templates"
      summary: "Delete a template"
      parameters:
      - name: "templateId"
        in: "path"
        description: "id of the template to delete"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
        
  # ============== COMMENTS ==============
  /comments/{memeId}:
    get:
      tags:
      - "comments"
      summary: "Get all comments on a meme"
      parameters:
      - name: "memeId"
        in: "path"
        description: "Id of meme to get comments of"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
  /comments:
    post:
      tags:
      - "comments"
      summary: "Comment on a meme"
      parameters:
      - in: "body"
        name: "body"
        description: "Comment to be added"
        required: true
        schema:
          $ref: "#/definitions/Comment"
      responses:
        200:
          description: "successful operation"

      
definitions:
  User:
    type: "object"
    required:
    - "username"
    - "passwordHash"
    - "salt"
    properties:
      username:
        type: "string"
      passwordHash:
        type: "string"
      salt:
        type: "string"
  Meme:
    type: "object"
    required:
    - "id"
    - "templateId"
    - "username"
    - "imageSource"
    - "votes"
    properties:
      id:
        type: "integer"
      templateId:
        type: "integer"
      username:
        type: "string"
      categoryId:
        type: "integer"
      name:
        type: "string"
      imageSource:
        type: "string"
      votes:
        type: "integer"
  MemeTemplate:
    type: "object"
    required:
    - "id"
    - "username"
    - "name"
    - "imageSource"
    properties:
      id:
        type: "integer"
      username:
        type: "string"
      name:
        type: "string"
      imageSource:
        type: "string"
  Comment:
    type: "object"
    required:
    - "id"
    - "memeId"
    - "username"
    - "text"
    - "votes"
    properties:
      id:
        type: "integer"
      memeId:
        type: "integer"
      username:
        type: "string"
      parentCommentId:
        type: "string"
      text:
        type: "string"
      votes:
        type: "integer"
  Category:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
