swagger: "2.0"
info:
  title: "Meme Platform"
  description: "Platform for memes."
  version: "1.0.0"
host: "TBA"

tags:
- name: "users"
  description: "Registered users"
- name: "memes"
  description: "Created meme posts"
- name: "templates"
  description: "Template images"
- name: "comments"
  description: "Comments on meme posts"
- name: "categories"
  description: "Categories of memes"
  
paths:
  # ============== USERS ==============
  /users:
    post:
      tags:
      - "users"
      summary: "Register a new user"
      consumes:
      - "application/json"
      responses:
        405:
          description: "Invalid input"
    get:
      tags:
      - "users"
      summary: "Get a list of users"
      produces:
      - "application/json"
      parameters:
      - name: "namequery"
      - name: "limit"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        400:
          description: "Invalid parameters or values"
        500:
          description: "Internal server error"
  /users/{username}:
    get:
      tags:
      - "users"
      summary: "Get a user"
    put:
      tags:
      - "users"
      summary: "Edits a user"
    delete:
      tags:
      - "users"
      summary: "Removes a user"
  
  # ============== MEMES ==============
  /memes:
    post:
      tags:
      - "memes"
      summary: "Post a new meme"
    get:
      tags:
      - "memes"
      summary: "Get a list of memes"
  /memes/{memeId}:
    get:
      tags:
      - "memes"
      summary: "Get a meme"
    delete:
      tags:
      - "memes"
      summary: "Delete a meme"
definitions:
  User:
    type: "object"
    required:
    - "username"
    - "passwordHash"
    - "salt"
    properties:
      username:
        type: "string"
      passwordHash:
        type: "string"
      salt:
        type: "string"
  Meme:
    type: "object"
    required:
    - "id"
    - "templateId"
    - "username"
    - "imageSource"
    - "votes"
    properties:
      id:
        type: "integer"
      templateId:
        type: "integer"
      username:
        type: "string"
      categoryId:
        type: "integer"
      name:
        type: "string"
      imageSource:
        type: "string"
      votes:
        type: "integer"
  MemeTemplate:
    type: "object"
    required:
    - "id"
    - "username"
    - "name"
    - "imageSource"
    properties:
      id:
        type: "integer"
      username:
        type: "string"
      name:
        type: "string"
      imageSource:
        type: "string"
  Comment:
    type: "object"
    required:
    - "id"
    - "memeId"
    - "username"
    - "text"
    - "votes"
    properties:
      id:
        type: "integer"
      memeId:
        type: "integer"
      username:
        type: "string"
      parentCommentId:
        type: "string"
      text:
        type: "string"
      votes:
        type: "integer"
  Category:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
